services:
  db:
    image: mysql:8.0
    container_name: streamify_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: streamify_db
      MYSQL_USER: streamify_user
      MYSQL_PASSWORD: streamify_pass
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/src/main/resources/db/migration:/docker-entrypoint-initdb.d
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: streamify_adminer
    ports:
      - "8081:8080"
    restart: unless-stopped

volumes:
  db_data: